export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';
export const GET_IMAGES_RESET = 'GET_IMAGES_RESET';

export const IMAGE_DETAILS_REQUEST = 'IMAGE_DETAILS_REQUEST';
export const IMAGE_DETAILS_SUCCESS = 'IMAGE_DETAILS_SUCCESS';
export const IMAGE_DETAILS_FAIL = 'IMAGE_DETAILS_FAIL';
export const IMAGE_DETAILS_RESET = 'IMAGE_DETAILS_RESET';

export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS';
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL';

export const IMAGE_RENAME_REQUEST = 'IMAGE_RENAME_REQUEST';
export const IMAGE_RENAME_SUCCESS = 'IMAGE_RENAME_SUCCESS';
export const IMAGE_RENAME_FAIL = 'IMAGE_RENAME_FAIL';
