# Generated by Django 3.2.9 on 2022-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ImageField(default='image-not-available.png', upload_to=''),
        ),
    ]
