# Generated by Django 3.2.9 on 2022-03-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220314_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
